### ISSUE TITLE
Problems with program installation

### ISSUE THREAD

**Issue by 20211203006ly** [UCLALES-SALSA/UCLALES-SALSA#9]
Hello，

I'm trying to install this program，but i get this error：
`File 'netcdf.mod' opened at (1) is not a GNU Fortran module file`
I have installed mpich and netcdf 4.3.0，and My Makefile is shown below.

`###############################################################
#
# Llocation of code (in $ROOT) and location where model is to be built $BIN
#
ROOT      :=$(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
BIN       = $(ROOT)/bin
ARCH      := $(shell uname)
#
# Generic Variables
#
SRC         =$(ROOT)/src
SRC_UTIL    =$(SRC)/src_util
SRC_LES     =$(SRC)/src_LES
SRC_SALSA   =$(SRC)/src_salsa
SRC_RAD     =$(SRC)/src_rad
SRC_EMIS    =$(SRC)/src_emission
SRC_SHARED  =$(SRC)/src_shared
SRC_IO      =$(SRC)/src_IO

VPATH = $(SRC_LES):$(SRC_SALSA):$(SRC_UTIL):$(SRC_RAD):  \
	$(SRC_EMIS):$(SRC_SHARED):$(SRC_IO):$(SRC)

ECHO    = /bin/echo
RM      = /bin/rm -f

ARCHIVE = ar rs
RANLIB =:
SEQFFLAGS = -I$(SRC)
MPIFFLAGS = -I$(SRC)
MPI = /public/software/mpi/5.0.2.044

# Linking the mpi has slightly changed for newer linux & library versions.
# Try switching between the two if it does not work.
MPILIB = -L$(MPI)/intel64/lib -lmpich
#MPILIB = -L$(MPI)/lib -lmpichfort

# This also varies on different computers
#MPIINC = -I$(MPI)/include/x86_64-linux-gnu/mpich
MPIINC = -I$(MPI)/intel64/include/mpich
NCDF = /public/software/mathlib/netcdf/4.3.0/intel
NCDFLIB = -L$(NCDF)/lib -lnetcdf -lnetcdff
NCDFINC = -I$(NCDF)/include
LIBS = '$(NCDFLIB) $(MPILIB)'
F90 = gfortran
MPIF90 = gfortran
FFLAGS = -O2 -fdefault-real-8 ${NCDFINC} $(MPIINC) -std=f2008 -fbounds-check  -g -fcheck=all -Wall -Wtabs  -fbacktrace -ffpe-trap=invalid,zero,overflow

LES_OUT_MPI=$(BIN)/les.mpi

LES_OUT_SEQ=$(BIN)/les.seq

default: mpi

all:  mpi seq

seq: $(LES_OUT_SEQ)

mpi: $(LES_OUT_MPI)

$(LES_OUT_SEQ): 
	cd $(SRC); $(MAKE) LES_ARC=seq                      \
	FFLAGS='$(FFLAGS) $(SEQFFLAGS)' F90=$(F90)          \
	OUT=$(LES_OUT_SEQ) LIBS=$(LIBS) SRCUTIL=$(SRC_UTIL) \
	SRCLES=$(SRC_LES) SRCSALSA=$(SRC_SALSA)             \
	SRCRAD=$(SRC_RAD) SRCEMIS=$(SRC_EMIS)               \
	SRCSHARED=$(SRC_SHARED) SRCIO=$(SRC_IO)

$(LES_OUT_MPI):
	cd $(SRC); $(MAKE) LES_ARC=mpi                      \
	FFLAGS='$(FFLAGS) $(MPIFFLAGS)' F90=$(MPIF90)       \
	OUT=$(LES_OUT_MPI) LIBS=$(LIBS) SRCUTIL=$(SRC_UTIL) \
	SRCLES=$(SRC_LES) SRCSALSA=$(SRC_SALSA)             \
	SRCRAD=$(SRC_RAD) SRCEMIS=$(SRC_EMIS)               \
	SRCSHARED=$(SRC_SHARED) SRCIO=$(SRC_IO)

.PHONY: $(LES_OUT_SEQ) 
.PHONY: $(LES_OUT_MPI)

#
# cleaning
# --------------------
#
clean: cleanmpi cleanseq 
	$(RM) $(SRC)/*mod $(SRC)/*.o

cleanmpi:
	$(ECHO) "cleaning mpi model"
	$(RM) core $(LES_OUT_MPI) $(SRC)/mpi/*mod $(LES_ARC_MPI)

cleanseq:
	$(ECHO) "clean sequential model"
	$(RM) core $(LES_OUT_SEQ) $(SRC)/seq/*mod $(LES_ARC_SEQ)

FORCE: 
.PRECIOUS: $(LIBS)`

I'd like to ask  how to solve this problem.
Thanks.

**Comment by TomiRaatikainen** [comment]
It sounds like your netcdf.mod is not compiled with the GNU Fortran (gfortran). In that case you need to reinstall netcdf and make sure that you are using the correct fortran compiler.

**Comment by 20211203006ly** [comment]
Thank you for your reply，I will try to reinstall NetCDF.
